export const iconMap = {
  dashboard: "LayoutDashboard",
  financeiro: "CircleDollarSign",
  produtos: "Package",
  estoque: "Boxes",
  vendas: "ShoppingCart",
  fornecedores: "Truck",
  compras: "ClipboardList",
  relatorios: "ChartNoAxesCombined",
  administracao: "Settings",
  usuarios: "Users",
  busca: "Search",
  filtros: "SlidersHorizontal",
  novo: "Plus",
  editar: "Pencil",
  arquivar: "Archive",
  excluir: "Trash2",
  cancelar: "XCircle",
  salvar: "Save",
  exportar: "Download",
  importar: "Upload",
  whatsapp: "MessageCircle",
  telefone: "Phone",
  email: "Mail",
  estoqueBaixo: "TriangleAlert",
  vendaConcluida: "CircleCheck",
  pagamento: "CreditCard",
  pix: "CircleDollarSign",
  caixa: "WalletCards",
  sincronizacao: "RefreshCw",
  offline: "CloudOff",
  online: "Cloud",
  cozinha: "CookingPot",
  bar: "Martini",
  espeto: "Flame",
  entrega: "Bike",
  mesa: "Armchair",
  comanda: "ReceiptText"
} as const;

export type AdegaIconName = keyof typeof iconMap;
export type LucideIconName = (typeof iconMap)[AdegaIconName];
